"""Field schema for the Residential Rental Listing Input Sheet.

Derived from the marked-up Triad MLS Residential Rental Input Form.
Rule applied: struck-through items are omitted; highlighted-and-not-struck
items are required; everything else is optional.

field types: text | number | select | multi | yesno | textarea
"dep" = show only when another field has a value: {"f": key, "eq": value} or {"f": key, "gt": 0}
"""

DIRS = ["N", "S", "E", "W", "NE", "NW", "SE", "SW"]
STREET_TYPES = ["Avenue", "Bend", "Boulevard", "Bypass", "Circle", "Court", "Drive", "Extension",
                "Lane", "Loop", "Manor", "Place", "Road", "Run", "Street", "Trail", "Way"]

SECTIONS = [
 {"name": "Address", "fields": [
   {"k": "subtype", "l": "Sub-Type", "t": "select", "req": True,
    "o": ["Stick/Site Built", "Cluster", "Condominium", "Manufactured", "Modular", "Townhouse", "Duplex"]},
   {"k": "county", "l": "County", "t": "text", "req": True},
   {"k": "street_no", "l": "Street #", "t": "text", "req": True},
   {"k": "pre_dir", "l": "Pre-Direction", "t": "select", "o": DIRS,
    "h": "Street direction that comes BEFORE the street name — e.g. 1314 W Dogwood Dr. Leave blank if none."},
   {"k": "street_name", "l": "Street Name", "t": "text", "req": True},
   {"k": "street_type", "l": "Street Type", "t": "select", "o": STREET_TYPES},
   {"k": "post_dir", "l": "Post-Direction", "t": "select", "o": DIRS,
    "h": "Direction that comes AFTER the street name — e.g. 400 Main St NE. Leave blank if none."},
   {"k": "unit_no", "l": "Unit #", "t": "text", "dep": {"f": "subtype", "in": ["Condominium", "Townhouse", "Duplex"]}},
   {"k": "unit_floor", "l": "Unit Floor #", "t": "text", "dep": {"f": "subtype", "in": ["Condominium", "Townhouse", "Duplex"]}},
   {"k": "city", "l": "City", "t": "text", "req": True},
   {"k": "zip", "l": "Zip Code", "t": "text", "req": True},
   {"k": "zip4", "l": "Zip +4", "t": "text"},
 ]},
 {"name": "Access", "fields": [
   {"k": "showmojo", "l": "ShowMojo Box Serial #", "t": "text",
    "ph": "123-45-678", "fmt": "showmojo", "pattern": r"\d{3}-\d{2}-\d{3}",
    "h": "Serial number on the ShowMojo box at the property. Format: ###-##-###"},
 ]},
 {"name": "Property", "fields": [
   {"k": "story", "l": "Story #", "t": "select",
    "o": ["1 Story", "1.5 Story", "2 Story", "2.5 Story", "3 Story", "4 Story",
          "1 Story w/ upper bonus room", "Split Foyer", "Split Level"]},
   {"k": "style", "l": "Style", "t": "multi",
    "o": ["A Frame", "Bungalow", "Cabin", "Cape Cod", "Chalet", "Colonial", "Condo Lower", "Condo Main",
          "Condo Upper", "Contemporary", "Cottage", "Double Wide", "Dutch Colonial", "Farmhouse",
          "French Provencial", "Georgian", "Log", "Ranch", "Salt Box", "Single Wide", "Split Foyer",
          "Split Level", "Traditional", "Transitional", "Tudor", "Victorian", "Williamsburg"]},
   {"k": "bedrooms", "l": "Bedrooms", "t": "number", "req": True},
   {"k": "full_baths", "l": "Full Baths", "t": "number", "req": True,
    "h": "Total for the property. Break out by floor below."},
   {"k": "half_baths", "l": "Half Baths", "t": "number", "req": True},
   {"k": "fb_main", "l": "Full Bath(s) Main", "t": "number"},
   {"k": "fb_upper", "l": "Full Bath(s) Upper", "t": "number"},
   {"k": "fb_lower", "l": "Full Bath(s) Lower", "t": "number"},
   {"k": "hb_main", "l": "Half Bath(s) Main", "t": "number"},
   {"k": "hb_upper", "l": "Half Bath(s) Upper", "t": "number"},
   {"k": "hb_lower", "l": "Half Bath(s) Lower", "t": "number"},
   {"k": "basement", "l": "Basement", "t": "yesno"},
   {"k": "basement_finish", "l": "Basement Finish", "t": "select", "dep": {"f": "basement", "eq": "Yes"},
    "o": ["Fully finished", "Semi-finished", "Unfinished"]},
   {"k": "fireplaces", "l": "# of Fireplaces", "t": "number"},
   {"k": "fireplace_loc", "l": "Fireplace Location", "t": "multi", "dep": {"f": "fireplaces", "gt": 0},
    "o": ["Basement", "Den", "Dining Room", "Great Room", "Keeping Room", "Kitchen", "Living Room",
          "Primary Bedroom", "Outdoor", "Playroom", "Remarks"]},
   {"k": "garage_spaces", "l": "Garage/Carport Spaces", "t": "number"},
   {"k": "garage_desc", "l": "Garage/Carport Description(s)", "t": "multi", "dep": {"f": "garage_spaces", "gt": 0},
    "o": ["Attached Carport", "Attached Garage", "Back Load Garage", "Basement Garage", "Detached Carport",
          "Detached Garage", "Front Load Garage", "Lower Level Garage", "None", "Side Load Garage"]},
   {"k": "parking", "l": "Parking", "t": "multi", "req": True,
    "o": ["Alley Parking", "Assigned", "Carport", "Driveway", "Field", "Garage", "Gravel", "Lighted Parking",
          "No Parking", "Parking Deck/Lot Av", "Parking Deck/Lot Inc", "Paved", "Public On-Street Parking",
          "Remarks", "Security", "Underground"]},
   {"k": "land", "l": "Land Description / Topography", "t": "multi",
    "o": ["Beach Front", "Clear", "Cleared Land", "Corner", "Creek", "Cul-De-Sac", "Dead End", "Fence(s)",
          "Flat", "Golf Course Lot", "Inland Waterway", "Lake", "Lake Front", "Lake View", "Land Lock-Ease",
          "Land Lock-No Ease", "Level", "Low", "Mountain", "Mountain View", "Multi Zones", "Part Cleared",
          "Part Fenced", "Part Wooded", "Pasture Lane", "Pond", "PUD", "Remarks", "River", "River Front",
          "Rolling", "Rural", "Secluded Lot", "Severe", "Sloping", "Steep", "Stream", "Subdivision",
          "Tier(ed) Watershed", "View", "Water View", "Wooded"]},
   {"k": "occupied", "l": "Occupied", "t": "yesno"},
   {"k": "furnished", "l": "Furnished", "t": "yesno"},
   {"k": "porch", "l": "Porch", "t": "yesno"},
   {"k": "fenced", "l": "Fenced", "t": "yesno"},
   {"k": "fence_extent", "l": "Fence Extent", "t": "select", "dep": {"f": "fenced", "eq": "Yes"},
    "o": ["Fully fenced (completely enclosed)", "Partially fenced"]},
   {"k": "pool", "l": "Pool", "t": "yesno", "req": True},
   {"k": "pool_features", "l": "Pool Features", "t": "multi", "dep": {"f": "pool", "eq": "Yes"},
    "o": ["Above Ground Pool", "Inground Pool", "Indoor Pool", "Neighborhood Pool", "Pool House", "Pool on Property"]},
   {"k": "misc", "l": "Miscellaneous", "t": "multi",
    "o": ["Balcony", "Barns", "Cable", "Great Room", "Guest Quarters", "Historic District", "Horses Allowed",
          "Plantation Shutters", "Public Transportation"]},
   {"k": "ext_finish", "l": "Exterior Finish", "t": "multi",
    "o": ["Aluminum", "Asbestos", "Block", "Brick", "Cementous Siding", "Composite Siding", "Formed Stone",
          "Frame", "Log", "Masonite-Type", "Pre-Cast Stone", "Stone", "Stucco", "Stucco-EIFS",
          "Stucco-Hard Coat", "Vinyl", "Wood", "Remarks"]},
   {"k": "ext_features", "l": "Exterior Features", "t": "multi",
    "o": ["Accent Lighting", "Boat House", "Boat Ramp", "Circle Drive", "Covered Porch", "Deck", "Dog Run",
          "Fenced", "Garden Space", "Gas Grill", "Gazebo", "Hot Tub", "Invisible Fencing", "Patio",
          "Paved Drive", "Pier", "Porch", "Privacy Fence", "Remarks", "Satellite Dish", "Screened Porch",
          "Security Lighting", "Sprinkler System", "Storage Building(s)", "Tennis Court", "Veranda/Breezeway"]},
 ]},
 {"name": "Interior", "fields": [
   {"k": "int_features", "l": "Interior Features", "t": "multi",
    "o": ["Alarm and/or Security System", "Arched Doorways", "Built-in Furniture", "Built-in Shelves",
          "Ceiling Fan(s)", "CO Detector", "Dead Bolt(s)", "Double Sided Fireplace", "Dryer Connection",
          "2nd Dryer Connection", "Electronic Air Filter", "Fireplace Blower", "Freestanding Tub",
          "Garage Door Opener(s)", "Garden Tub", "Gas Logs", "Hot Tub", "Humidifier", "Inlaw Suite",
          "Intercom", "Interior Attic Fan", "Jetted Tub", "Kitchen Island", "Laundry Chute",
          "Laundry Room Main", "Laundry Room - 2nd", "Laundry Room Basement", "Pantry", "Remarks", "Sauna",
          "Separate Shower", "Skylight", "Smoke Alarm", "Solid Surface Counter", "Sump Pump",
          "Surround Sound", "Tiler Counter", "Vacuum System", "Vaulted Ceilings", "Washer Connection",
          "2nd Washer Connection", "Wet Bar"]},
   {"k": "access_features", "l": "Accessibility Features", "t": "multi",
    "o": ["2 or More Accessible Exits", "Accessible Kitchen Appliances", "Accessible Parking",
          "All Width 36 Inches or More", "Bath 60 Inch Turning Radius", "Bath Grab Bars",
          "Bath Lever Faucets", "Bath Low Mirrors", "Bath Raised Toilet", "Bath Roll-In Shower",
          "Bath Roll-Under Sink", "Bath Scald Control Faucet", "Closet Bars 15-28 Inches",
          "Door Width 32 In or More", "Doors - Lever Handle", "Doors-Recede", "Doors-Swing In", "Elevator",
          "Entry Slope Less than 1 Ft.", "Exterior Curb Cuts", "Garage Door Ht. Greater 84 In",
          "Kitchen 60 Inch Turn Radius", "Kitchen Low Cabinetry", "Kitchen Low Counters",
          "Kitchen Modified Range", "Kitchen Raised Dishwasher", "Kitchen Roll-Under Sink",
          "Kitchen Side Open Oven", "Lowered Light Switched", "Mobile Friendly Flooring",
          "No Interior Steps", "Other - See Remarks", "Pool Power Lift", "Pool Ramp Entry",
          "Ramps(s) - Main Level", "Remote Devices", "Stair Lift", "Thresholds 5/8 Inches",
          "Vehicle Transfer Area", "Wheelchair Height Mailbox", "Wheelchair Height Shelves",
          "Zero Grade Entry"]},
   {"k": "amenities", "l": "Amenities", "t": "text"},
   {"k": "appliances", "l": "Appliances", "t": "multi",
    "o": ["Appliance Center", "Attached Microwave Oven", "Built-in Grill", "Built-in Oven", "Built-in Range",
          "Built-in Refrigerator", "Compactor", "Convection Oven", "Convection Microwave", "Cook Top",
          "Dishwasher", "Disposal", "Double Oven", "Draft Range", "Dual-Fuel Range", "Exhaust Fan",
          "Free Standing Range", "Gas Cooktop", "Hot Water Dispenser", "Ice Maker", "Remarks",
          "Slide-in Oven/Range", "Smooth Cooktop", "Vent Hood", "Warming Drawer", "Water Purifier"]},
   {"k": "flooring", "l": "Flooring", "t": "multi",
    "o": ["Brick", "Carpet", "Carpet over Wood", "Concrete Slab/Grade", "Engineered", "Laminate", "Remarks",
          "Stone", "Terrazzo", "Tile", "Vinyl", "Vinyl Plank", "Wood"]},
 ]},
 {"name": "Utilities", "fields": [
   {"k": "heating", "l": "Heating", "t": "multi",
    "o": ["Active Solar", "Boiler", "Circulator", "Circulator Hot Water", "Dual Fuel System",
          "Electric Baseboard", "Electric Ceiling", "Fireplace", "Floor Furnace", "Forced Warm Air",
          "Geo-Thermal", "Ground Water Heat Pump", "Heat Pump", "Multiple Systems", "Multi Zone", "No Heat",
          "Passive Solar", "Radiant Floor", "Radiator", "Suspended Ceiling Heat", "Wall Furnace",
          "Wood Furnace", "Remarks"]},
   {"k": "heating_fuel", "l": "Heating Fuel", "t": "multi",
    "o": ["Electric", "Natural Gas", "No Fuel", "Oil", "Propane", "Solar", "Wood Fuel", "Remarks"]},
   {"k": "cooling", "l": "Cooling", "t": "multi",
    "o": ["Attic Fan", "Attic Ventilator", "Central", "Chiller", "Ground Water", "Heat Pump", "Multi Zone",
          "Multiple Systems", "Single Level Only", "Wall Unit(s)", "Window Unit(s)", "None", "Remarks"]},
   {"k": "water_heater", "l": "Water Heater", "t": "select", "req": True,
    "o": ["Electric", "Gas", "None", "Solar", "Tankless", "Unknown", "Wood"]},
   {"k": "water", "l": "Water", "t": "select", "req": True,
    "o": ["Community/Subdivision", "None", "Private", "Public", "Public Availability", "Shared Well",
          "Spring", "Well"]},
   {"k": "sewer", "l": "Sewer", "t": "select", "req": True,
    "o": ["Community", "Private", "Public", "Public Availability", "Septic", "Shared Septic", "Remarks"]},
   {"k": "energy", "l": "Energy Features", "t": "multi",
    "o": ["Energy Star Rate", "Generator", "Generator Auto Start", "Insulated Doors", "Insulated Windows",
          "LEED Certified", "NAHB Certified Green", "None", "Storm Doors", "Storm Windows"]},
 ]},
 {"name": "Submission", "fields": [
   {"k": "completed_by", "l": "Completed by", "t": "text", "h": "Who walked the property."},
   {"k": "notes", "l": "Notes for admin / support", "t": "textarea",
    "h": "Anything the person entering the listing should know (not an MLS remarks field)."},
 ]},
]

def all_fields():
    for s in SECTIONS:
        for f in s["fields"]:
            yield s["name"], f

def required_keys():
    return [f["k"] for _, f in all_fields() if f.get("req")]
